name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Go to project folder
        run: cd ilp_submission_1

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 23

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
