name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 23

      - name: Build with Maven
        run: mvn -B clean install -f ./ilp_submission_1/pom.xml

      - name: Run integration tests
        run: mvn test -f ./ilp_submission_1/pom.xml

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16  # or 18, etc.

      - name: Install newman
        run: npm install -g newman

      - name: Run Service
        run: ./mvnw spring-boot:run --quiet

      - name: Run Postman tests
        run: newman run ./ilp_submission_1/systemTestCollection.json --reporters cli

